-- NOTE: This file is auto generated by ./sql-generator

-- AssetDeletedChecksumRepository.upsert
insert into
  "asset_deleted_checksum" (
    "ownerId",
    "checksum",
    "assetId",
    "originalFileName"
  )
values
  ($1, $2, $3, $4)
on conflict ("ownerId", "checksum") do update
set
  "assetId" = "excluded"."assetId",
  "originalFileName" = "excluded"."originalFileName",
  "deletedAt" = now(),
  "reimportedAt" = $5,
  "reimportMode" = $6,
  "notifiedAt" = $7

-- AssetDeletedChecksumRepository.get
select
  "assetId",
  "originalFileName",
  "deletedAt"
from
  "asset_deleted_checksum"
where
  "ownerId" = $1
  and "checksum" = $2

-- AssetDeletedChecksumRepository.getByChecksums
select
  "checksum",
  "assetId"
from
  "asset_deleted_checksum"
where
  "ownerId" = $1
  and "checksum" in ($2)

-- AssetDeletedChecksumRepository.markReimported
update "asset_deleted_checksum"
set
  "reimportedAt" = now(),
  "reimportMode" = $1,
  "notifiedAt" = $2
where
  "ownerId" = $3
  and "checksum" = $4

-- AssetDeletedChecksumRepository.getPendingNotification
select
  "reimportMode",
  count(*) as "count"
from
  "asset_deleted_checksum"
where
  "ownerId" = $1
  and "reimportedAt" is not null
  and "notifiedAt" is null
group by
  "reimportMode"

-- AssetDeletedChecksumRepository.markNotified
update "asset_deleted_checksum"
set
  "notifiedAt" = now()
where
  "ownerId" = $1
  and "reimportedAt" is not null
  and "notifiedAt" is null

-- AssetDeletedChecksumRepository.forgetAssets
delete from "asset_deleted_checksum" using "asset"
where
  "asset"."ownerId" = "asset_deleted_checksum"."ownerId"
  and "asset"."checksum" = "asset_deleted_checksum"."checksum"
  and "asset"."id" in ($1)

-- AssetDeletedChecksumRepository.forgetTrashed
delete from "asset_deleted_checksum" using "asset"
where
  "asset"."checksum" = "asset_deleted_checksum"."checksum"
  and "asset"."ownerId" = $1
  and "asset"."status" = $2
  and "asset_deleted_checksum"."ownerId" = $3

-- AssetDeletedChecksumRepository.getCount
select
  count(*) as "count"
from
  "asset_deleted_checksum"
where
  "ownerId" = $1

-- AssetDeletedChecksumRepository.deleteAll
delete from "asset_deleted_checksum"
where
  "ownerId" = $1
