-- NOTE: This file is auto generated by ./sql-generator

-- AutoStackRepository.getForAutoStackJob
select
  "asset"."id",
  "asset"."ownerId",
  "stack"."source" as "stackSource",
  "asset"."type",
  "asset"."visibility",
  "asset"."deletedAt",
  "asset"."fileCreatedAt",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset_job_status"."autoStackedAt",
  "asset_quality"."updatedAt" as "qualityUpdatedAt"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "stack" on "stack"."id" = "asset"."stackId"
  left join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
where
  "asset"."id" = $1::uuid

-- AutoStackRepository.getTimeline
select
  "asset"."id",
  "asset"."fileCreatedAt",
  smart_search.embedding <=> lag(smart_search.embedding) over (
    order by
      asset."fileCreatedAt",
      asset.id
  ) as "distance"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "smart_search" on "smart_search"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1::uuid
  and "asset"."fileCreatedAt" >= $2
  and "asset"."fileCreatedAt" <= $3
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset_exif"."make" = $4
  and "asset_exif"."model" = $5
order by
  "asset"."fileCreatedAt" asc,
  "asset"."id" asc

-- AutoStackRepository.getCandidates
select
  "asset"."id",
  "asset"."type",
  "asset"."visibility",
  "asset"."isFavorite",
  "asset"."isPrivate",
  "asset"."stackId",
  "asset"."originalFileName",
  "asset"."fileCreatedAt",
  "asset"."createdAt",
  "asset_exif"."make",
  "asset_exif"."model",
  "smart_search"."embedding",
  "asset_job_status"."facesRecognizedAt",
  "asset_job_status"."autoStackedAt",
  "asset_quality"."sharpness",
  "asset_quality"."exposureClipped",
  "asset_quality"."assetId" is not null as "hasQuality",
  exists (
    select
    from
      "stack_auto_exclusion"
    where
      "stack_auto_exclusion"."assetId" = "asset"."id"
  ) as "isExcluded",
  exists (
    select
    from
      "stack"
    where
      "stack"."id" = "asset"."stackId"
      and (
        "stack"."source" != 'auto'
        or exists (
          select
          from
            "asset" as "member"
            inner join "stack_auto_exclusion" on "stack_auto_exclusion"."assetId" = "member"."id"
          where
            "member"."stackId" = "stack"."id"
        )
      )
  ) as "isInUserStack",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset_face_attribute"."detected",
          "asset_face_attribute"."eyeBlinkLeft",
          "asset_face_attribute"."eyeBlinkRight",
          "asset_face_attribute"."smile",
          "asset_face_attribute"."yaw",
          "asset_face_attribute"."sharpness",
          "asset_face"."personGroupId",
          "asset_face"."imageWidth",
          "asset_face"."imageHeight",
          "asset_face"."boundingBoxX1",
          "asset_face"."boundingBoxY1",
          "asset_face"."boundingBoxX2",
          "asset_face"."boundingBoxY2"
        from
          "asset_face"
          left join "asset_face_attribute" on "asset_face_attribute"."faceId" = "asset_face"."id"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
      ) as agg
  ) as "faces"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "smart_search" on "smart_search"."assetId" = "asset"."id"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1::uuid
  and "asset"."id" = any ($2::uuid[])
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
order by
  "asset"."fileCreatedAt" asc,
  "asset"."id" asc

-- AutoStackRepository.getStacks
select
  "stack"."id",
  "stack"."primaryAssetId",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset"."id"
        from
          "asset"
        where
          "asset"."stackId" = "stack"."id"
          and "asset"."deletedAt" is null
      ) as agg
  ) as "assets"
from
  "stack"
where
  "stack"."id" = any ($1::uuid[])
  and "stack"."source" = 'auto'

-- AutoStackRepository.updatePrimaryAsset
update "stack"
set
  "primaryAssetId" = $1
where
  "id" = $2::uuid
  and "source" = 'auto'

-- AutoStackRepository.streamForAutoStack
select
  "asset"."id"
from
  "asset"
  inner join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
where
  "asset_job_status"."autoStackedAt" is null
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and exists (
    select
    from
      "user_metadata"
    where
      "user_metadata"."userId" = "asset"."ownerId"
      and "user_metadata"."key" = 'preferences'
      and user_metadata.value -> 'autoStack' ->> 'enabled' = $1
  )
order by
  "asset"."fileCreatedAt" asc

-- AutoStackRepository.resetAutoStackedAt
update "asset_job_status"
set
  "autoStackedAt" = $1
where
  "asset_job_status"."autoStackedAt" is not null

-- AutoStackRepository.setAutoStackedAt
insert into
  "asset_job_status" ("assetId", "autoStackedAt")
values
  ($1, $2)
on conflict ("assetId") do update
set
  "autoStackedAt" = $3

-- AutoStackRepository.getStackAssetIds
select
  "asset"."id",
  "asset"."ownerId"
from
  "asset"
where
  "asset"."stackId" = $1::uuid

-- AutoStackRepository.getExclusions
select
  *
from
  "stack_auto_exclusion"
where
  "stack_auto_exclusion"."assetId" = any ($1::uuid[])
