-- NOTE: This file is auto generated by ./sql-generator

-- CustomViewRepository.getAll
select
  "view"."id",
  "view"."ownerId",
  "view"."access",
  "view"."includeAll",
  "view"."includeUntagged",
  "view"."privateAssets",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'include'
    ),
    '{}'
  ) as "includeTagIds",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'exclude'
    ),
    '{}'
  ) as "excludeTagIds",
  "view"."name",
  "view"."order",
  "view"."isDefault",
  "view"."createdAt",
  "view"."updatedAt"
from
  "view"
where
  "view"."ownerId" = $1::uuid
  and exists (
    select
    from
      "view_tag"
      inner join "tag_closure" on "tag_closure"."id_descendant" = "view_tag"."tagId"
    where
      "view_tag"."viewId" = "view"."id"
      and "tag_closure"."id_ancestor" = $2::uuid
  )
order by
  "view"."order" asc,
  "view"."createdAt" asc

-- CustomViewRepository.get
select
  "view"."id",
  "view"."ownerId",
  "view"."access",
  "view"."includeAll",
  "view"."includeUntagged",
  "view"."privateAssets",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'include'
    ),
    '{}'
  ) as "includeTagIds",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'exclude'
    ),
    '{}'
  ) as "excludeTagIds",
  "view"."name",
  "view"."order",
  "view"."isDefault",
  "view"."createdAt",
  "view"."updatedAt"
from
  "view"
where
  "view"."id" = $1::uuid

-- CustomViewRepository.getDefault
select
  "view"."id",
  "view"."ownerId",
  "view"."access",
  "view"."includeAll",
  "view"."includeUntagged",
  "view"."privateAssets",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'include'
    ),
    '{}'
  ) as "includeTagIds",
  coalesce(
    (
      select
        array_agg("view_tag"."tagId") as "ids"
      from
        "view_tag"
      where
        "view_tag"."viewId" = "view"."id"
        and "view_tag"."mode" = 'exclude'
    ),
    '{}'
  ) as "excludeTagIds"
from
  "view"
where
  "view"."ownerId" = $1::uuid
  and "view"."isDefault" = $2

-- CustomViewRepository.delete
delete from "view"
where
  "id" = $1::uuid

-- CustomViewRepository.getChangedAssetIds
select
  "asset"."id"
from
  "asset"
where
  (
    "asset"."ownerId" = $1::uuid
    or "asset"."ownerId" in (
      select
        "partner"."sharedById"
      from
        "partner"
      where
        "partner"."sharedWithId" = $2::uuid
    )
    or exists (
      select
      from
        "album_asset"
        inner join "album_user" on "album_user"."albumId" = "album_asset"."albumId"
      where
        "album_asset"."assetId" = "asset"."id"
        and "album_user"."userId" = $3::uuid
    )
  )
  and (
    (
      (
        not exists (
          select
          from
            "tag_asset"
            inner join "tag" on "tag"."id" = "tag_asset"."tagId"
          where
            "tag_asset"."assetId" = "asset"."id"
            and "tag"."userId" = $4
        )
        or exists (
          select
          from
            "tag_asset"
            inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
          where
            "tag_asset"."assetId" = "asset"."id"
            and "tag_closure"."id_ancestor" = any ($5::uuid[])
        )
      )
      and not exists (
        select
        from
          "tag_asset"
          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
        where
          "tag_asset"."assetId" = "asset"."id"
          and "tag_closure"."id_ancestor" = any ($6::uuid[])
      )
      and "asset"."isPrivate" = $7
    )
  ) is distinct from (true)

-- CustomViewRepository.touchAssets
update "asset"
set
  "updatedAt" = clock_timestamp()
where
  "id" = any ($1::uuid[])
update "asset_exif"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" = any ($1::uuid[])
update "album_asset"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" = any ($1::uuid[])
update "stack"
set
  "updatedAt" = clock_timestamp()
where
  "primaryAssetId" = any ($1::uuid[])
update "asset_face"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" = any ($1::uuid[])
update "memory_asset"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" = any ($1::uuid[])
