-- NOTE: This file is auto generated by ./sql-generator

-- FaceAttributeRepository.getForFaceAttributesJob
select
  "asset"."id",
  "asset"."visibility",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewFile",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset_face"."id",
          "asset_face"."imageWidth",
          "asset_face"."imageHeight",
          "asset_face"."boundingBoxX1",
          "asset_face"."boundingBoxY1",
          "asset_face"."boundingBoxX2",
          "asset_face"."boundingBoxY2"
        from
          "asset_face"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
        order by
          "asset_face"."id"
      ) as agg
  ) as "faces"
from
  "asset"
where
  "asset"."id" = $1

-- FaceAttributeRepository.streamForFaceAttributesJob
select
  "asset"."id"
from
  "asset"
  inner join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
where
  "asset"."visibility" != $1
  and "asset"."deletedAt" is null
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $2
  )
  and "asset_job_status"."facesRecognizedAt" is not null
  and (
    not exists (
      select
      from
        "asset_quality"
      where
        "asset_quality"."assetId" = "asset"."id"
    )
    or exists (
      select
      from
        "asset_face"
        left join "asset_face_attribute" on "asset_face_attribute"."faceId" = "asset_face"."id"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and "asset_face_attribute"."faceId" is null
    )
  )
order by
  "asset"."fileCreatedAt" desc

-- FaceAttributeRepository.upsert
begin
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" = $1
for key share
commit

-- FaceAttributeRepository.getQualityByAssetIds
select
  "asset_quality".*
from
  "asset_quality"
where
  "asset_quality"."assetId" = any ($1::uuid[])

-- FaceAttributeRepository.getFaceAttributesByAssetIds
select
  "asset_face_attribute".*,
  "asset_face"."assetId",
  "asset_face"."imageWidth",
  "asset_face"."imageHeight",
  "asset_face"."boundingBoxX1",
  "asset_face"."boundingBoxY1",
  "asset_face"."boundingBoxX2",
  "asset_face"."boundingBoxY2",
  "asset_face"."isVisible"
from
  "asset_face_attribute"
  inner join "asset_face" on "asset_face"."id" = "asset_face_attribute"."faceId"
where
  "asset_face"."assetId" = any ($1::uuid[])
  and "asset_face"."deletedAt" is null
