-- NOTE: This file is auto generated by ./sql-generator

-- PersonSuggestionRepository.getTypicalFaceNorm
select
  percentile_cont(0.5) within group (
    order by
      vector_norm (face_search.embedding)
  ) as "norm"
from
  "asset_face"
  inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  (
    "asset"."ownerId" = $1
    and "asset"."deletedAt" is null
    and "asset"."visibility" in ($2, $3)
    and "asset_face"."deletedAt" is null
    and "asset_face"."isVisible" = $4
    and "asset_face"."isWholeAsset" = $5
  )

-- PersonSuggestionRepository.getPersonSimilarities
with
  "centroid" as materialized (
    select
      "person"."personGroupId",
      "person"."name",
      avg(l2_normalize (face_search.embedding)) as "embedding",
      count(*) as "faces"
    from
      "asset_face"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
      and "person"."ownerId" = $1
    where
      "person"."isHidden" = $2
      and (
        "asset"."ownerId" = $3
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($4, $5)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $6
        and "asset_face"."isWholeAsset" = $7
      )
      and vector_norm (face_search.embedding) >= $8
    group by
      "person"."personGroupId",
      "person"."name"
  )
select
  "candidate"."personGroupId" as "personGroupId",
  "target"."personGroupId" as "targetPersonGroupId",
  "target"."name" != $9 as "isNamed",
  "candidate"."faces" as "faces",
  "target"."faces" as "targetFaces",
  1 - (candidate.embedding <=> target.embedding) as "similarity"
from
  "centroid" as "candidate"
  inner join "centroid" as "target" on "target"."personGroupId" != "candidate"."personGroupId"
where
  "candidate"."name" = $10
  and (
    "target"."name" != $11
    or "candidate"."personGroupId" < "target"."personGroupId"
  )
  and 1 - (candidate.embedding <=> target.embedding) >= $12

-- PersonSuggestionRepository.getFaceSimilarities
with
  "centroid" as materialized (
    select
      "person"."personGroupId",
      avg(l2_normalize (face_search.embedding)) as "embedding",
      count(*) as "faces"
    from
      "asset_face"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
      and "person"."ownerId" = $1
    where
      "person"."isHidden" = $2
      and "person"."name" != $3
      and (
        "asset"."ownerId" = $4
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($5, $6)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $7
        and "asset_face"."isWholeAsset" = $8
      )
      and vector_norm (face_search.embedding) >= $9
    group by
      "person"."personGroupId"
  )
select
  "asset_face"."id" as "faceId",
  "centroid"."personGroupId" as "targetPersonGroupId",
  "centroid"."faces" as "targetFaces",
  1 - (face_search.embedding <=> centroid.embedding) as "similarity"
from
  "asset_face"
  inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  inner join "centroid" on true
where
  "asset_face"."personGroupId" is null
  and (
    "asset"."ownerId" = $10
    and "asset"."deletedAt" is null
    and "asset"."visibility" in ($11, $12)
    and "asset_face"."deletedAt" is null
    and "asset_face"."isVisible" = $13
    and "asset_face"."isWholeAsset" = $14
  )
  and vector_norm (face_search.embedding) >= $15
  and least(
    asset_face."boundingBoxX2" - asset_face."boundingBoxX1",
    asset_face."boundingBoxY2" - asset_face."boundingBoxY1"
  ) >= $16::float8 * greatest(asset_face."imageWidth", asset_face."imageHeight")
  and 1 - (face_search.embedding <=> centroid.embedding) >= $17

-- PersonSuggestionRepository.getSpreadFaceIds
select
  "face"."id",
  "face"."personGroupId"
from
  (
    select
      "asset_face"."id",
      "asset_face"."personGroupId",
      row_number() over (
        partition by
          asset_face."personGroupId"
        order by
          asset."fileCreatedAt",
          asset_face.id
      ) as "position",
      count(*) over (
        partition by
          asset_face."personGroupId"
      ) as "total"
    from
      "asset_face"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."personGroupId" = any ($1::uuid[])
      and (
        "asset"."ownerId" = $2
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($3, $4)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $5
        and "asset_face"."isWholeAsset" = $6
      )
      and vector_norm (face_search.embedding) >= $7
      and least(
        asset_face."boundingBoxX2" - asset_face."boundingBoxX1",
        asset_face."boundingBoxY2" - asset_face."boundingBoxY1"
      ) >= $8::float8 * greatest(asset_face."imageWidth", asset_face."imageHeight")
  ) as "face"
where
  (face.position - 1) % ceil(face.total::float8 / $9)::int = 0

-- PersonSuggestionRepository.getNearestPersonFaces
begin
set
  local vchordrq.probes = 1
select
  "query"."faceId",
  "neighbor"."personGroupId",
  "neighbor"."assetId",
  "neighbor"."similarity"
from
  "face_search" as "query"
  inner join lateral (
    select
      "asset_face"."personGroupId",
      "asset_face"."assetId",
      1 - (face_search.embedding <=> query.embedding) as "similarity"
    from
      "face_search"
      inner join "asset_face" on "asset_face"."id" = "face_search"."faceId"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."personGroupId" is not null
      and "asset_face"."id" != "query"."faceId"
      and (
        "asset"."ownerId" = $1
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($2, $3)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $4
        and "asset_face"."isWholeAsset" = $5
      )
      and vector_norm (face_search.embedding) >= $6
    order by
      face_search.embedding <=> query.embedding
    limit
      $7
  ) as "neighbor" on true
where
  "query"."faceId" = any ($8::uuid[])
commit

-- PersonSuggestionRepository.getCandidateStatistics
select
  coalesce("asset_face"."personGroupId", "asset_face"."id") as "id",
  count(distinct ("asset"."id")) as "assets",
  count(
    distinct (asset."localDateTime" at time zone 'UTC')::date
  ) as "days",
  max("asset"."fileCreatedAt") as "latest"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($2, $3)
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $4
  and (
    "asset_face"."personGroupId" = any ($5::uuid[])
    or "asset_face"."id" = any ($6::uuid[])
  )
group by
  coalesce("asset_face"."personGroupId", "asset_face"."id")

-- PersonSuggestionRepository.getSharedAssetShares
select
  pair."candidateId",
  pair."targetId",
  count(distinct asset.id) as total,
  count(distinct asset.id) filter (
    where
      exists (
        select
          1
        from
          asset_face as other
        where
          other."assetId" = asset.id
          and other."personGroupId" = pair."targetId"
          and other."deletedAt" is null
          and other."isVisible" is true
          and other."isWholeAsset" is false
      )
  ) as shared
from
  (
    select
      unnest($1::uuid[]) as "candidateId",
      unnest($2::uuid[]) as "targetId"
  ) as pair
  inner join asset_face on asset_face."personGroupId" = pair."candidateId"
  inner join asset on asset.id = asset_face."assetId"
where
  asset."ownerId" = $3
  and asset."deletedAt" is null
  and asset_face."deletedAt" is null
  and asset_face."isVisible" is true
group by
  pair."candidateId",
  pair."targetId"
union all
select
  pair."candidateId",
  pair."targetId",
  count(distinct asset.id) as total,
  count(distinct asset.id) filter (
    where
      exists (
        select
          1
        from
          asset_face as other
        where
          other."assetId" = asset.id
          and other."personGroupId" = pair."targetId"
          and other."deletedAt" is null
          and other."isVisible" is true
          and other."isWholeAsset" is false
      )
  ) as shared
from
  (
    select
      unnest($4::uuid[]) as "candidateId",
      unnest($5::uuid[]) as "targetId"
  ) as pair
  inner join asset_face on asset_face.id = pair."candidateId"
  inner join asset on asset.id = asset_face."assetId"
where
  asset."ownerId" = $6
  and asset."deletedAt" is null
group by
  pair."candidateId",
  pair."targetId"

-- PersonSuggestionRepository.getAll
select
  *
from
  "person_suggestion"
where
  "ownerId" = $1

-- PersonSuggestionRepository.get
select
  *
from
  "person_suggestion"
where
  "id" = $1

-- PersonSuggestionRepository.getByPair
select
  *
from
  "person_suggestion"
where
  "ownerId" = $1
  and (
    (
      "personGroupId" = $2
      and "targetPersonGroupId" = $3
    )
    or (
      "personGroupId" = $4
      and "targetPersonGroupId" = $5
    )
  )

-- PersonSuggestionRepository.create
insert into
  "person_suggestion" (
    "ownerId",
    "kind",
    "personGroupId",
    "targetPersonGroupId",
    "score"
  )
values
  ($1, $2, $3, $4, $5)
returning
  *

-- PersonSuggestionRepository.update
update "person_suggestion"
set
  "status" = $1
where
  "id" = $2
returning
  *

-- PersonSuggestionRepository.deleteAll
delete from "person_suggestion"
where
  "id" = any ($1::uuid[])

-- PersonSuggestionRepository.reopenSkipped
update "person_suggestion"
set
  "status" = $1,
  "answeredAt" = $2
where
  "ownerId" = $3
  and "status" = $4
  and "answeredAt" < $5

-- PersonSuggestionRepository.getPending
select
  "person_suggestion".*
from
  "person_suggestion"
  inner join "person" as "target" on "target"."personGroupId" = "person_suggestion"."targetPersonGroupId"
  and "target"."ownerId" = $1
  left join "person" as "candidate" on "candidate"."personGroupId" = "person_suggestion"."personGroupId"
  and "candidate"."ownerId" = $2
  left join "asset_face" as "face" on "face"."id" = "person_suggestion"."faceId"
  left join "person" as "facePerson" on "facePerson"."personGroupId" = "face"."personGroupId"
  and "facePerson"."ownerId" = $3
where
  "person_suggestion"."ownerId" = $4
  and "person_suggestion"."status" = $5
  and "target"."isHidden" = $6
  and (
    (
      "candidate"."isHidden" = $7
      and "candidate"."name" = $8
    )
    or (
      "face"."id" is not null
      and (
        "face"."personGroupId" is null
        or "facePerson"."name" = $9
      )
      and (
        "face"."personGroupId" is null
        or "face"."personGroupId" != "person_suggestion"."targetPersonGroupId"
      )
    )
  )
  and exists (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      (
        "asset_face"."personGroupId" = "person_suggestion"."personGroupId"
        or "asset_face"."id" = "person_suggestion"."faceId"
      )
      and (
        "asset"."ownerId" = $10
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($11, $12)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $13
        and "asset_face"."isWholeAsset" = $14
        and (
          "asset"."isPrivate" = $15
          and (
            (
              (
                not exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag"."userId" = $16
                )
                and (
                  "asset"."visibility" != 'hidden'
                  or not exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag"."userId" = $17
                      )
                  )
                )
              )
              or (
                exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag_closure"."id_ancestor" = any ($18::uuid[])
                )
                or (
                  "asset"."visibility" = 'hidden'
                  and exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag_closure"."id_ancestor" = any ($19::uuid[])
                      )
                  )
                )
              )
            )
            and (
              not exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
                  and "tag_closure"."id_ancestor" = any ($20::uuid[])
              )
              and (
                "asset"."visibility" != 'hidden'
                or not exists (
                  select
                  from
                    "asset" as "live_photo_still"
                  where
                    "live_photo_still"."livePhotoVideoId" = "asset"."id"
                    and exists (
                      select
                      from
                        "tag_asset"
                        inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                      where
                        "tag_asset"."assetId" = "live_photo_still"."id"
                        and "tag_closure"."id_ancestor" = any ($21::uuid[])
                    )
                )
              )
            )
            and "asset"."isPrivate" = $22
          )
        )
      )
  )
  and exists (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."personGroupId" = "person_suggestion"."targetPersonGroupId"
      and (
        "asset"."ownerId" = $23
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($24, $25)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $26
        and "asset_face"."isWholeAsset" = $27
        and (
          "asset"."isPrivate" = $28
          and (
            (
              (
                not exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag"."userId" = $29
                )
                and (
                  "asset"."visibility" != 'hidden'
                  or not exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag"."userId" = $30
                      )
                  )
                )
              )
              or (
                exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag_closure"."id_ancestor" = any ($31::uuid[])
                )
                or (
                  "asset"."visibility" = 'hidden'
                  and exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag_closure"."id_ancestor" = any ($32::uuid[])
                      )
                  )
                )
              )
            )
            and (
              not exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
                  and "tag_closure"."id_ancestor" = any ($33::uuid[])
              )
              and (
                "asset"."visibility" != 'hidden'
                or not exists (
                  select
                  from
                    "asset" as "live_photo_still"
                  where
                    "live_photo_still"."livePhotoVideoId" = "asset"."id"
                    and exists (
                      select
                      from
                        "tag_asset"
                        inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                      where
                        "tag_asset"."assetId" = "live_photo_still"."id"
                        and "tag_closure"."id_ancestor" = any ($34::uuid[])
                    )
                )
              )
            )
            and "asset"."isPrivate" = $35
          )
        )
      )
  )
order by
  "person_suggestion"."priority" desc,
  "person_suggestion"."id"
limit
  $36
offset
  $37

-- PersonSuggestionRepository.getPendingCount
select
  count(*) as "count"
from
  "person_suggestion"
  inner join "person" as "target" on "target"."personGroupId" = "person_suggestion"."targetPersonGroupId"
  and "target"."ownerId" = $1
  left join "person" as "candidate" on "candidate"."personGroupId" = "person_suggestion"."personGroupId"
  and "candidate"."ownerId" = $2
  left join "asset_face" as "face" on "face"."id" = "person_suggestion"."faceId"
  left join "person" as "facePerson" on "facePerson"."personGroupId" = "face"."personGroupId"
  and "facePerson"."ownerId" = $3
where
  "person_suggestion"."ownerId" = $4
  and "person_suggestion"."status" = $5
  and "target"."isHidden" = $6
  and (
    (
      "candidate"."isHidden" = $7
      and "candidate"."name" = $8
    )
    or (
      "face"."id" is not null
      and (
        "face"."personGroupId" is null
        or "facePerson"."name" = $9
      )
      and (
        "face"."personGroupId" is null
        or "face"."personGroupId" != "person_suggestion"."targetPersonGroupId"
      )
    )
  )
  and exists (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      (
        "asset_face"."personGroupId" = "person_suggestion"."personGroupId"
        or "asset_face"."id" = "person_suggestion"."faceId"
      )
      and (
        "asset"."ownerId" = $10
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($11, $12)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $13
        and "asset_face"."isWholeAsset" = $14
        and (
          "asset"."isPrivate" = $15
          and (
            (
              (
                not exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag"."userId" = $16
                )
                and (
                  "asset"."visibility" != 'hidden'
                  or not exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag"."userId" = $17
                      )
                  )
                )
              )
              or (
                exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag_closure"."id_ancestor" = any ($18::uuid[])
                )
                or (
                  "asset"."visibility" = 'hidden'
                  and exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag_closure"."id_ancestor" = any ($19::uuid[])
                      )
                  )
                )
              )
            )
            and (
              not exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
                  and "tag_closure"."id_ancestor" = any ($20::uuid[])
              )
              and (
                "asset"."visibility" != 'hidden'
                or not exists (
                  select
                  from
                    "asset" as "live_photo_still"
                  where
                    "live_photo_still"."livePhotoVideoId" = "asset"."id"
                    and exists (
                      select
                      from
                        "tag_asset"
                        inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                      where
                        "tag_asset"."assetId" = "live_photo_still"."id"
                        and "tag_closure"."id_ancestor" = any ($21::uuid[])
                    )
                )
              )
            )
            and "asset"."isPrivate" = $22
          )
        )
      )
  )
  and exists (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."personGroupId" = "person_suggestion"."targetPersonGroupId"
      and (
        "asset"."ownerId" = $23
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($24, $25)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $26
        and "asset_face"."isWholeAsset" = $27
        and (
          "asset"."isPrivate" = $28
          and (
            (
              (
                not exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag"."userId" = $29
                )
                and (
                  "asset"."visibility" != 'hidden'
                  or not exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag"."userId" = $30
                      )
                  )
                )
              )
              or (
                exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag_closure"."id_ancestor" = any ($31::uuid[])
                )
                or (
                  "asset"."visibility" = 'hidden'
                  and exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag_closure"."id_ancestor" = any ($32::uuid[])
                      )
                  )
                )
              )
            )
            and (
              not exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
                  and "tag_closure"."id_ancestor" = any ($33::uuid[])
              )
              and (
                "asset"."visibility" != 'hidden'
                or not exists (
                  select
                  from
                    "asset" as "live_photo_still"
                  where
                    "live_photo_still"."livePhotoVideoId" = "asset"."id"
                    and exists (
                      select
                      from
                        "tag_asset"
                        inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                      where
                        "tag_asset"."assetId" = "live_photo_still"."id"
                        and "tag_closure"."id_ancestor" = any ($34::uuid[])
                    )
                )
              )
            )
            and "asset"."isPrivate" = $35
          )
        )
      )
  )

-- PersonSuggestionRepository.getAnswered
select
  *
from
  "person_suggestion"
where
  "ownerId" = $1
  and "status" != $2
  and "answeredAt" is not null
order by
  "answeredAt" desc
limit
  $3

-- PersonSuggestionRepository.getShownFaces
select distinct
  on ("face"."tile") "face"."id",
  "face"."assetId",
  "face"."updatedAt",
  "face"."fileCreatedAt"
from
  (
    select
      "asset_face"."id",
      "asset_face"."assetId",
      "asset_face"."updatedAt",
      "asset"."fileCreatedAt",
      ntile($1) over (
        order by
          asset."fileCreatedAt",
          asset_face.id
      ) as "tile",
      (
        asset_face."boundingBoxX2" - asset_face."boundingBoxX1"
      )::float8 * (
        asset_face."boundingBoxY2" - asset_face."boundingBoxY1"
      ) / greatest(
        asset_face."imageWidth" * asset_face."imageHeight",
        1
      ) as "size"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."personGroupId" = $2
      and (
        "asset"."ownerId" = $3
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($4, $5)
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $6
        and "asset_face"."isWholeAsset" = $7
        and (
          "asset"."isPrivate" = $8
          and (
            (
              (
                not exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag"."userId" = $9
                )
                and (
                  "asset"."visibility" != 'hidden'
                  or not exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag"."userId" = $10
                      )
                  )
                )
              )
              or (
                exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "asset"."id"
                    and "tag_closure"."id_ancestor" = any ($11::uuid[])
                )
                or (
                  "asset"."visibility" = 'hidden'
                  and exists (
                    select
                    from
                      "asset" as "live_photo_still"
                    where
                      "live_photo_still"."livePhotoVideoId" = "asset"."id"
                      and exists (
                        select
                        from
                          "tag_asset"
                          inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                        where
                          "tag_asset"."assetId" = "live_photo_still"."id"
                          and "tag_closure"."id_ancestor" = any ($12::uuid[])
                      )
                  )
                )
              )
            )
            and (
              not exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
                  and "tag_closure"."id_ancestor" = any ($13::uuid[])
              )
              and (
                "asset"."visibility" != 'hidden'
                or not exists (
                  select
                  from
                    "asset" as "live_photo_still"
                  where
                    "live_photo_still"."livePhotoVideoId" = "asset"."id"
                    and exists (
                      select
                      from
                        "tag_asset"
                        inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                      where
                        "tag_asset"."assetId" = "live_photo_still"."id"
                        and "tag_closure"."id_ancestor" = any ($14::uuid[])
                    )
                )
              )
            )
            and "asset"."isPrivate" = $15
          )
        )
      )
  ) as "face"
order by
  "face"."tile",
  "face"."size" desc,
  "face"."id"

-- PersonSuggestionRepository.getMostSimilarFaces
with
  "query" as (
    select
      avg(l2_normalize (face_search.embedding)) as "embedding"
    from
      "asset_face"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
    where
      "asset_face"."personGroupId" = $1
      and "asset_face"."deletedAt" is null
  )
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."updatedAt",
  "asset"."fileCreatedAt"
from
  "asset_face"
  inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  inner join "query" on true
where
  "asset_face"."personGroupId" = $2
  and (
    "asset"."ownerId" = $3
    and "asset"."deletedAt" is null
    and "asset"."visibility" in ($4, $5)
    and "asset_face"."deletedAt" is null
    and "asset_face"."isVisible" = $6
    and "asset_face"."isWholeAsset" = $7
    and (
      "asset"."isPrivate" = $8
      and (
        (
          (
            not exists (
              select
              from
                "tag_asset"
                inner join "tag" on "tag"."id" = "tag_asset"."tagId"
              where
                "tag_asset"."assetId" = "asset"."id"
                and "tag"."userId" = $9
            )
            and (
              "asset"."visibility" != 'hidden'
              or not exists (
                select
                from
                  "asset" as "live_photo_still"
                where
                  "live_photo_still"."livePhotoVideoId" = "asset"."id"
                  and exists (
                    select
                    from
                      "tag_asset"
                      inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                    where
                      "tag_asset"."assetId" = "live_photo_still"."id"
                      and "tag"."userId" = $10
                  )
              )
            )
          )
          or (
            exists (
              select
              from
                "tag_asset"
                inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
              where
                "tag_asset"."assetId" = "asset"."id"
                and "tag_closure"."id_ancestor" = any ($11::uuid[])
            )
            or (
              "asset"."visibility" = 'hidden'
              and exists (
                select
                from
                  "asset" as "live_photo_still"
                where
                  "live_photo_still"."livePhotoVideoId" = "asset"."id"
                  and exists (
                    select
                    from
                      "tag_asset"
                      inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                    where
                      "tag_asset"."assetId" = "live_photo_still"."id"
                      and "tag_closure"."id_ancestor" = any ($12::uuid[])
                  )
              )
            )
          )
        )
        and (
          not exists (
            select
            from
              "tag_asset"
              inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag_closure"."id_ancestor" = any ($13::uuid[])
          )
          and (
            "asset"."visibility" != 'hidden'
            or not exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag_closure"."id_ancestor" = any ($14::uuid[])
                )
            )
          )
        )
        and "asset"."isPrivate" = $15
      )
    )
  )
order by
  face_search.embedding <=> query.embedding
limit
  $16

-- PersonSuggestionRepository.getShownAssetCount
select
  count(distinct ("asset"."id")) as "count"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "asset_face"."personGroupId" = $1
  and "asset"."ownerId" = $2
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($3, $4)
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $5
  and (
    "asset"."isPrivate" = $6
    and (
      (
        (
          not exists (
            select
            from
              "tag_asset"
              inner join "tag" on "tag"."id" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag"."userId" = $7
          )
          and (
            "asset"."visibility" != 'hidden'
            or not exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag"."userId" = $8
                )
            )
          )
        )
        or (
          exists (
            select
            from
              "tag_asset"
              inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag_closure"."id_ancestor" = any ($9::uuid[])
          )
          or (
            "asset"."visibility" = 'hidden'
            and exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag_closure"."id_ancestor" = any ($10::uuid[])
                )
            )
          )
        )
      )
      and (
        not exists (
          select
          from
            "tag_asset"
            inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
          where
            "tag_asset"."assetId" = "asset"."id"
            and "tag_closure"."id_ancestor" = any ($11::uuid[])
        )
        and (
          "asset"."visibility" != 'hidden'
          or not exists (
            select
            from
              "asset" as "live_photo_still"
            where
              "live_photo_still"."livePhotoVideoId" = "asset"."id"
              and exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "live_photo_still"."id"
                  and "tag_closure"."id_ancestor" = any ($12::uuid[])
              )
          )
        )
      )
      and "asset"."isPrivate" = $13
    )
  )

-- PersonSuggestionRepository.getDifferentPersonGroupIds
select
  "targetPersonGroupId"
from
  "person_suggestion"
where
  "faceId" = $1
  and "status" = $2

-- PersonSuggestionRepository.getFacesDifferentFrom
select
  "faceId"
from
  "person_suggestion"
where
  "faceId" = any ($1::uuid[])
  and "targetPersonGroupId" = $2
  and "status" = $3

-- PersonSuggestionRepository.getPeopleDifferentFrom
select
  "personGroupId",
  "targetPersonGroupId"
from
  "person_suggestion"
where
  "ownerId" = $1
  and "status" = $2
  and (
    (
      "personGroupId" = $3
      and "targetPersonGroupId" = any ($4::uuid[])
    )
    or (
      "targetPersonGroupId" = $5
      and "personGroupId" = any ($6::uuid[])
    )
  )

-- PersonSuggestionRepository.moveToPerson
begin
delete from "person_suggestion"
where
  "ownerId" = $1
  and (
    "status" in ($2, $3)
    or (
      "personGroupId" = $4
      and "targetPersonGroupId" = $5
    )
    or (
      "personGroupId" = $6
      and "targetPersonGroupId" = $7
    )
  )
  and (
    "personGroupId" = $8
    or "targetPersonGroupId" = $9
  )
delete from "person_suggestion" as "moved"
where
  "moved"."ownerId" = $1
  and exists (
    select
      "kept"."id"
    from
      "person_suggestion" as "kept"
    where
      "kept"."ownerId" = "moved"."ownerId"
      and (
        (
          "moved"."personGroupId" = $2
          and (
            (
              "kept"."personGroupId" = $3
              and "kept"."targetPersonGroupId" = "moved"."targetPersonGroupId"
            )
            or (
              "kept"."targetPersonGroupId" = $4
              and "kept"."personGroupId" = "moved"."targetPersonGroupId"
            )
          )
        )
        or (
          "moved"."targetPersonGroupId" = $5
          and (
            (
              "kept"."targetPersonGroupId" = $6
              and (
                "kept"."personGroupId" = "moved"."personGroupId"
                or "kept"."faceId" = "moved"."faceId"
              )
            )
            or (
              "kept"."personGroupId" = $7
              and "kept"."targetPersonGroupId" = "moved"."personGroupId"
            )
          )
        )
      )
  )
update "person_suggestion"
set
  "personGroupId" = $1
where
  "ownerId" = $2
  and "personGroupId" = $3
update "person_suggestion"
set
  "targetPersonGroupId" = $1
where
  "ownerId" = $2
  and "targetPersonGroupId" = $3
commit

-- PersonSuggestionRepository.getFaceForCrop
select
  "asset_face"."id",
  "asset_face"."boundingBoxX1" as "x1",
  "asset_face"."boundingBoxY1" as "y1",
  "asset_face"."boundingBoxX2" as "x2",
  "asset_face"."boundingBoxY2" as "y2",
  "asset_face"."imageWidth" as "oldWidth",
  "asset_face"."imageHeight" as "oldHeight",
  "asset_face"."frameTimestamp",
  "asset_face"."isWholeAsset",
  "asset"."id" as "assetId",
  "asset"."ownerId",
  "asset"."type",
  "asset"."originalPath",
  "asset"."isPrivate",
  "asset_exif"."orientation" as "exifOrientation",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath",
  (
    select
      to_json(obj)
    from
      (
        select
          "asset_video"."index",
          "asset_video"."codecName",
          "asset_video"."profile",
          "asset_video"."level",
          "asset_video"."bitrate",
          "asset_exif"."exifImageWidth" as "width",
          "asset_exif"."exifImageHeight" as "height",
          "asset_video"."pixelFormat",
          "asset_video"."frameCount",
          "asset_exif"."fps" as "frameRate",
          "asset_video"."timeBase",
          case
            when "asset_exif"."orientation" = '6' then -90
            when "asset_exif"."orientation" = '8' then 90
            when "asset_exif"."orientation" = '3' then 180
            else 0
          end as "rotation",
          "asset_video"."colorPrimaries",
          "asset_video"."colorMatrix",
          "asset_video"."colorTransfer",
          "asset_video"."dvProfile",
          "asset_video"."dvLevel",
          "asset_video"."dvBlSignalCompatibilityId"
        from
          (
            select
              1
          ) as "dummy"
        where
          "asset_video"."assetId" is not null
      ) as obj
  ) as "videoStream"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "asset_video" on "asset_video"."assetId" = "asset"."id"
where
  "asset_face"."id" = $1
  and "asset_face"."deletedAt" is null
  and "asset"."deletedAt" is null

-- PersonSuggestionRepository.isAssetInScope
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" = $1
  and (
    "asset"."isPrivate" = $2
    and (
      (
        (
          not exists (
            select
            from
              "tag_asset"
              inner join "tag" on "tag"."id" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag"."userId" = $3
          )
          and (
            "asset"."visibility" != 'hidden'
            or not exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag"."userId" = $4
                )
            )
          )
        )
        or (
          exists (
            select
            from
              "tag_asset"
              inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag_closure"."id_ancestor" = any ($5::uuid[])
          )
          or (
            "asset"."visibility" = 'hidden'
            and exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag_closure"."id_ancestor" = any ($6::uuid[])
                )
            )
          )
        )
      )
      and (
        not exists (
          select
          from
            "tag_asset"
            inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
          where
            "tag_asset"."assetId" = "asset"."id"
            and "tag_closure"."id_ancestor" = any ($7::uuid[])
        )
        and (
          "asset"."visibility" != 'hidden'
          or not exists (
            select
            from
              "asset" as "live_photo_still"
            where
              "live_photo_still"."livePhotoVideoId" = "asset"."id"
              and exists (
                select
                from
                  "tag_asset"
                  inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "live_photo_still"."id"
                  and "tag_closure"."id_ancestor" = any ($8::uuid[])
              )
          )
        )
      )
      and "asset"."isPrivate" = $9
    )
  )

-- PersonSuggestionRepository.deleteOpenForFace
delete from "person_suggestion"
where
  "faceId" = $1
  and "id" != $2
  and "status" in ($3, $4)

-- PersonSuggestionRepository.getFaceIdsOfPerson
select
  "asset_face"."id"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "asset_face"."personGroupId" = $1
  and "asset"."ownerId" = $2

-- PersonSuggestionRepository.moveFaces
update "asset_face"
set
  "personGroupId" = $1
where
  "asset_face"."id" = any ($2::uuid[])
  and "asset_face"."personGroupId" = $3
returning
  "asset_face"."id"

-- PersonSuggestionRepository.getFacesStillWith
select
  "asset_face"."id"
from
  "asset_face"
where
  "asset_face"."id" = any ($1::uuid[])
  and "asset_face"."personGroupId" = $2

-- PersonSuggestionRepository.restoreGroup
insert into
  "person_group" ("id", "clusterGroupId")
select
  $1::uuid as "id",
  "user"."clusterGroupId"
from
  "user"
where
  "user"."id" = $2
on conflict ("id") do nothing

-- PersonSuggestionRepository.getShownFacesByIds
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."updatedAt",
  "asset"."fileCreatedAt"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "asset_face"."id" = any ($1::uuid[])
  and (
    "asset"."ownerId" = $2
    and "asset"."deletedAt" is null
    and "asset"."visibility" in ($3, $4)
    and "asset_face"."deletedAt" is null
    and "asset_face"."isVisible" = $5
    and "asset_face"."isWholeAsset" = $6
    and (
      "asset"."isPrivate" = $7
      and (
        (
          (
            not exists (
              select
              from
                "tag_asset"
                inner join "tag" on "tag"."id" = "tag_asset"."tagId"
              where
                "tag_asset"."assetId" = "asset"."id"
                and "tag"."userId" = $8
            )
            and (
              "asset"."visibility" != 'hidden'
              or not exists (
                select
                from
                  "asset" as "live_photo_still"
                where
                  "live_photo_still"."livePhotoVideoId" = "asset"."id"
                  and exists (
                    select
                    from
                      "tag_asset"
                      inner join "tag" on "tag"."id" = "tag_asset"."tagId"
                    where
                      "tag_asset"."assetId" = "live_photo_still"."id"
                      and "tag"."userId" = $9
                  )
              )
            )
          )
          or (
            exists (
              select
              from
                "tag_asset"
                inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
              where
                "tag_asset"."assetId" = "asset"."id"
                and "tag_closure"."id_ancestor" = any ($10::uuid[])
            )
            or (
              "asset"."visibility" = 'hidden'
              and exists (
                select
                from
                  "asset" as "live_photo_still"
                where
                  "live_photo_still"."livePhotoVideoId" = "asset"."id"
                  and exists (
                    select
                    from
                      "tag_asset"
                      inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                    where
                      "tag_asset"."assetId" = "live_photo_still"."id"
                      and "tag_closure"."id_ancestor" = any ($11::uuid[])
                  )
              )
            )
          )
        )
        and (
          not exists (
            select
            from
              "tag_asset"
              inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
              and "tag_closure"."id_ancestor" = any ($12::uuid[])
          )
          and (
            "asset"."visibility" != 'hidden'
            or not exists (
              select
              from
                "asset" as "live_photo_still"
              where
                "live_photo_still"."livePhotoVideoId" = "asset"."id"
                and exists (
                  select
                  from
                    "tag_asset"
                    inner join "tag_closure" on "tag_closure"."id_descendant" = "tag_asset"."tagId"
                  where
                    "tag_asset"."assetId" = "live_photo_still"."id"
                    and "tag_closure"."id_ancestor" = any ($13::uuid[])
                )
            )
          )
        )
        and "asset"."isPrivate" = $14
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc
limit
  $15

-- PersonSuggestionRepository.deleteBySource
delete from "person_suggestion"
where
  "ownerId" = $1
  and "source" = $2
  and "status" = $3
