-- NOTE: This file is auto generated by ./sql-generator

-- SessionRepository.get
select
  "id",
  "expiresAt",
  "pinExpiresAt",
  "privateModeExpiresAt",
  "viewId",
  "viewExpiresAt",
  "oauthBearerToken"
from
  "session"
where
  "id" = $1

-- SessionRepository.isPendingSyncReset
select
  "isPendingSyncReset"
from
  "session"
where
  "id" = $1

-- SessionRepository.getByToken
select
  "session"."id",
  "session"."updatedAt",
  "session"."pinExpiresAt",
  "session"."privateModeExpiresAt",
  "session"."viewId",
  "session"."viewExpiresAt",
  "session"."appVersion",
  (
    select
      to_json(obj)
    from
      (
        select
          "user"."id",
          "user"."name",
          "user"."email",
          "user"."isAdmin",
          "user"."quotaUsageInBytes",
          "user"."quotaSizeInBytes"
        from
          "user"
        where
          "user"."id" = "session"."userId"
          and "user"."deletedAt" is null
      ) as obj
  ) as "user",
  (
    select
      to_json(obj)
    from
      (
        select
          "view"."id",
          "view"."ownerId",
          "view"."access",
          "view"."includeAll",
          "view"."includeUntagged",
          "view"."privateAssets",
          coalesce(
            (
              select
                array_agg("view_tag"."tagId") as "ids"
              from
                "view_tag"
              where
                "view_tag"."viewId" = "view"."id"
                and "view_tag"."mode" = 'include'
            ),
            '{}'
          ) as "includeTagIds",
          coalesce(
            (
              select
                array_agg("view_tag"."tagId") as "ids"
              from
                "view_tag"
              where
                "view_tag"."viewId" = "view"."id"
                and "view_tag"."mode" = 'exclude'
            ),
            '{}'
          ) as "excludeTagIds"
        from
          "view"
        where
          "view"."id" = "session"."viewId"
          and "view"."ownerId" = "session"."userId"
      ) as obj
  ) as "view",
  (
    select
      to_json(obj)
    from
      (
        select
          "view"."id",
          "view"."ownerId",
          "view"."access",
          "view"."includeAll",
          "view"."includeUntagged",
          "view"."privateAssets",
          coalesce(
            (
              select
                array_agg("view_tag"."tagId") as "ids"
              from
                "view_tag"
              where
                "view_tag"."viewId" = "view"."id"
                and "view_tag"."mode" = 'include'
            ),
            '{}'
          ) as "includeTagIds",
          coalesce(
            (
              select
                array_agg("view_tag"."tagId") as "ids"
              from
                "view_tag"
              where
                "view_tag"."viewId" = "view"."id"
                and "view_tag"."mode" = 'exclude'
            ),
            '{}'
          ) as "excludeTagIds"
        from
          "view"
        where
          "view"."ownerId" = "session"."userId"
          and "view"."isDefault" = $1
      ) as obj
  ) as "defaultView"
from
  "session"
where
  "session"."token" = $2
  and (
    "session"."expiresAt" is null
    or "session"."expiresAt" > $3
  )

-- SessionRepository.getByUserId
select
  "session".*
from
  "session"
  inner join "user" on "user"."id" = "session"."userId"
  and "user"."deletedAt" is null
where
  "session"."userId" = $1
  and (
    "session"."expiresAt" is null
    or "session"."expiresAt" > $2
  )
order by
  "session"."updatedAt" desc,
  "session"."createdAt" desc

-- SessionRepository.delete
delete from "session"
where
  "id" = $1::uuid

-- SessionRepository.invalidateAll
delete from "session"
where
  "userId" = $1
  and "id" != $2

-- SessionRepository.lockAll
update "session"
set
  "pinExpiresAt" = $1,
  "privateModeExpiresAt" = $2,
  "viewId" = $3,
  "viewExpiresAt" = $4
where
  "userId" = $5

-- SessionRepository.resetSyncProgress
begin
update "session"
set
  "isPendingSyncReset" = $1
where
  "id" = $2
delete from "session_sync_checkpoint"
where
  "sessionId" = $1
commit
