-- NOTE: This file is auto generated by ./sql-generator

-- TagRepository.get
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId",
  "tag"."isHidden"
from
  "tag"
where
  "id" = $1

-- TagRepository.getByValue
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId",
  "tag"."isHidden"
from
  "tag"
where
  "userId" = $1
  and "value" = $2

-- TagRepository.upsertValue
with
  "created_tag" as (
    insert into
      "tag" ("userId", "value", "parentId")
    values
      ($1, $2, $3)
    on conflict ("userId", "value") do update
    set
      "parentId" = $4
    returning
      *
  ),
  "created_tag_closures" as (
    insert into
      "tag_closure" ("id_ancestor", "id_descendant")
    select
      "created_tag"."id" as "id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
    union all
    select
      "tag_closure"."id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
      inner join "tag_closure" on "tag_closure"."id_descendant" = "created_tag"."parentId"
    on conflict do nothing
  )
select
  *
from
  "created_tag"

-- TagRepository.getAll
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId",
  "tag"."isHidden"
from
  "tag"
where
  "userId" = $1
  and not exists (
    select
    from
      "tag_closure"
      inner join "tag" as "hidden_tag" on "hidden_tag"."id" = "tag_closure"."id_ancestor"
    where
      "tag_closure"."id_descendant" = "tag"."id"
      and "hidden_tag"."isHidden" = $2
  )
order by
  "value"

-- TagRepository.create
with
  "created_tag" as (
    insert into
      "tag" ("userId", "color", "value")
    values
      ($1, $2, $3)
    returning
      *
  ),
  "created_tag_closures" as (
    insert into
      "tag_closure" ("id_ancestor", "id_descendant")
    select
      "created_tag"."id" as "id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
    union all
    select
      "tag_closure"."id_ancestor",
      "created_tag"."id" as "id_descendant"
    from
      "created_tag"
      inner join "tag_closure" on "tag_closure"."id_descendant" = "created_tag"."parentId"
    on conflict do nothing
  )
select
  *
from
  "created_tag"

-- TagRepository.update
begin
select
  "value"
from
  "tag"
where
  "id" = $1
update "tag"
set
  "value" = $1,
  "color" = $2
where
  "id" = $3
returning
  *
rollback

-- TagRepository.delete
delete from "tag"
where
  "id" = $1

-- TagRepository.addAssetIds
begin
select
  "assetId"
from
  "asset_exif"
where
  "assetId" in ($1)
order by
  "assetId"
for update
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)
rollback

-- TagRepository.removeAssetIds
begin
select
  "assetId"
from
  "asset_exif"
where
  "assetId" in ($1)
order by
  "assetId"
for update
delete from "tag_asset"
where
  "tagId" = $1
  and "assetId" in ($2)
insert into
  "asset_exif" ("assetId", "tags", "lockedProperties")
select
  "asset"."id",
  array(
    (
      select
        "tag"."value"
      from
        "tag_asset"
        inner join "tag" on "tag"."id" = "tag_asset"."tagId"
      where
        "tag_asset"."assetId" = "asset"."id"
      order by
        "tag"."value"
    )
  ) as "tags",
  array['tags']::character varying[] as "lockedProperties"
from
  "asset"
where
  "asset"."id" in ($1)
on conflict ("assetId") do update
set
  "tags" = "excluded"."tags",
  "lockedProperties" = array(
    select distinct
      unnest(
        "asset_exif"."lockedProperties" || array['tags']::character varying[]
      )
  )
commit

-- TagRepository.upsertAssetIds
begin
select
  "assetId"
from
  "asset_exif"
where
  "assetId" in ($1)
order by
  "assetId"
for update
insert into
  "tag_asset" ("assetId", "tagIds")
values
  ($1, $2)
on conflict do nothing
returning
  *
rollback

-- TagRepository.replaceAssetTags
begin
delete from "tag_asset"
where
  "assetId" = $1
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)
on conflict do nothing
returning
  *
rollback
