-- NOTE: This file is auto generated by ./sql-generator

-- TakeoutRepository.getFolder
select
  *
from
  "takeout_folder"
where
  "userId" = $1

-- TakeoutRepository.getAllFolders
select
  "userId",
  "folderName"
from
  "takeout_folder"

-- TakeoutRepository.createFolder
insert into
  "takeout_folder" ("userId", "folderName")
values
  ($1, $2)
returning
  *

-- TakeoutRepository.deleteFolder
delete from "takeout_folder"
where
  "userId" = $1

-- TakeoutRepository.getOrphanFolders
select
  "takeout_folder"."userId" as "userId",
  "takeout_folder"."folderName" as "folderName"
from
  "takeout_folder"
  left join "user" on "user"."id" = "takeout_folder"."userId"
where
  "user"."id" is null

-- TakeoutRepository.getSettings
select
  "settings"
from
  "takeout_settings"
where
  "userId" = $1

-- TakeoutRepository.upsertSettings
insert into
  "takeout_settings" ("userId", "settings", "updatedAt")
values
  ($1, $2, now())
on conflict ("userId") do update
set
  "settings" = "excluded"."settings",
  "updatedAt" = now()

-- TakeoutRepository.createUpload
insert into
  "takeout_upload" ("userId", "fileName", "size")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.getUpload
select
  *
from
  "takeout_upload"
where
  "id" = $1

-- TakeoutRepository.getUploadByName
select
  *
from
  "takeout_upload"
where
  "userId" = $1
  and "fileName" = $2

-- TakeoutRepository.getUploads
select
  *
from
  "takeout_upload"
where
  "userId" = $1
order by
  "createdAt" asc

-- TakeoutRepository.getAllUploads
select
  "id",
  "userId",
  "fileName",
  "size"
from
  "takeout_upload"

-- TakeoutRepository.touchUpload
update "takeout_upload"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.deleteUpload
delete from "takeout_upload"
where
  "id" = $1

-- TakeoutRepository.getExportsByUser
select
  *
from
  "takeout_export"
where
  "userId" = $1
order by
  "exportedAt" desc

-- TakeoutRepository.getExport
select
  *
from
  "takeout_export"
where
  "id" = $1

-- TakeoutRepository.createExport
insert into
  "takeout_export" ("userId", "exportKey", "exportedAt")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.updateExport
update "takeout_export"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.deleteExport
delete from "takeout_export"
where
  "id" = $1

-- TakeoutRepository.getExportsNeedingAnalysis
select
  "id"
from
  "takeout_export"
where
  (
    "analyzedAt" is null
    or "analysisInputsAt" > "analyzedAt"
  )
  and "analysisInputsAt" is not null

-- TakeoutRepository.getPartsByUser
select
  *
from
  "takeout_part"
where
  "userId" = $1

-- TakeoutRepository.getPartsByExport
select
  *
from
  "takeout_part"
where
  "exportId" = $1
order by
  "segment" asc nulls first,
  "partNumber" asc

-- TakeoutRepository.getPart
select
  *
from
  "takeout_part"
where
  "id" = $1

-- TakeoutRepository.createPart
insert into
  "takeout_part" ("exportId", "userId", "fileName")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.updatePart
update "takeout_part"
set
where
  "id" = $1

-- TakeoutRepository.deletePart
delete from "takeout_part"
where
  "id" = $1

-- TakeoutRepository.markPartMissing
begin
delete from "takeout_entry"
where
  "partId" = $1
update "takeout_part"
set
  "isMissing" = $1,
  "catalogStatus" = $2,
  "entryCount" = $3
where
  "id" = $4
commit

-- TakeoutRepository.updatePartsOfRun
update "takeout_part"
set
  "catalogStatus" = $1
where
  "lastReadRunId" = $2
  and "catalogStatus" = $3

-- TakeoutRepository.resetReadingParts
update "takeout_part"
set
  "catalogStatus" = $1
where
  "catalogStatus" = $2
  and (
    "lastReadRunId" is null
    or not exists (
      select
        "takeout_run"."id"
      from
        "takeout_run"
      where
        "takeout_run"."id" = "takeout_part"."lastReadRunId"
        and "takeout_run"."status" in ($3, $4, $5, $6, $7, $8)
    )
  )

-- TakeoutRepository.deleteEntriesOfPart
delete from "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.getMaxEntrySeq
select
  max("seq") as "maxSeq"
from
  "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.countEntries
select
  count(*) as "count"
from
  "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.getEntriesForSkip
select
  "seq",
  "path",
  "size",
  "kind",
  "checksum"
from
  "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.deleteEntriesOfExport
delete from "takeout_entry"
where
  "exportId" = $1

-- TakeoutRepository.getMediaEntryPaths
select
  "path"
from
  "takeout_entry"
where
  "exportId" = $1
  and "kind" = $2

-- TakeoutRepository.getEntriesWithoutSample
select
  "takeout_entry"."id" as "id",
  "takeout_entry"."partId" as "partId",
  "takeout_entry"."seq" as "seq",
  "takeout_entry"."path" as "path",
  "takeout_entry"."size" as "size",
  "takeout_entry"."checksum" as "checksum",
  "takeout_part"."fileName" as "partName"
from
  "takeout_entry"
  inner join "takeout_part" on "takeout_part"."id" = "takeout_entry"."partId"
where
  "takeout_entry"."exportId" = $1
  and "takeout_entry"."kind" = $2
  and "takeout_entry"."sample" is null
  and "takeout_entry"."sampleSkipped" is null
  and "takeout_entry"."checksum" is not null

-- TakeoutRepository.updateEntry
update "takeout_entry"
set
where
  "id" = $1

-- TakeoutRepository.getCataloguedMediaPaths
select
  "takeout_entry"."path" as "path"
from
  "takeout_entry"
  inner join "takeout_part" on "takeout_part"."id" = "takeout_entry"."partId"
where
  "takeout_entry"."exportId" = $1
  and "takeout_entry"."kind" = $2
  and "takeout_part"."catalogVersion" = $3
  and "takeout_part"."catalogStatus" = $4

-- TakeoutRepository.getEntryOccurrences
select
  "takeout_entry"."checksum" as "checksum",
  "takeout_entry"."partId" as "partId",
  "takeout_entry"."seq" as "seq",
  "takeout_entry"."path" as "path",
  "takeout_entry"."size" as "size",
  "takeout_entry"."endOffset" as "endOffset",
  "takeout_part"."fileName" as "partName",
  "takeout_part"."kind" as "kind"
from
  "takeout_entry"
  inner join "takeout_part" on "takeout_part"."id" = "takeout_entry"."partId"
where
  "takeout_entry"."exportId" = $1
  and "takeout_entry"."checksum" in ($2)
  and "takeout_part"."catalogVersion" = $3
  and "takeout_part"."catalogStatus" != $4
  and "takeout_part"."isMissing" = $5

-- TakeoutRepository.getUploadAssetSizesOver
select distinct
  "asset_exif"."fileSizeInByte" as "size"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."libraryId" is null
  and "asset_exif"."fileSizeInByte" > $2

-- TakeoutRepository.getUploadAssetsBySize
select
  "asset"."id" as "id",
  "asset"."originalPath" as "originalPath"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."libraryId" is null
  and "asset_exif"."fileSizeInByte" = $2
limit
  $3

-- TakeoutRepository.createRun
insert into
  "takeout_run" ("userId", "exportId")
values
  ($1, $2)
returning
  *

-- TakeoutRepository.getRun
select
  *
from
  "takeout_run"
where
  "id" = $1

-- TakeoutRepository.getRunsByExport
select
  *
from
  "takeout_run"
where
  "exportId" = $1
order by
  "createdAt" desc

-- TakeoutRepository.getActiveRun
select
  *
from
  "takeout_run"
where
  "userId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7, $8)
order by
  "createdAt" desc

-- TakeoutRepository.getActiveRunForExport
select
  *
from
  "takeout_run"
where
  "exportId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7, $8)

-- TakeoutRepository.getAdoptableRun
select
  *
from
  "takeout_run"
where
  "exportId" = $1
  and "status" in ($2, $3)
  and "hasStaging" = $4
  and "supersededBy" is null
order by
  "createdAt" desc
limit
  $5

-- TakeoutRepository.getRunsSupersededBy
select
  *
from
  "takeout_run"
where
  "supersededBy" = $1

-- TakeoutRepository.updateRun
update "takeout_run"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.updateRunIfLeased
update "takeout_run"
set
  "updatedAt" = now()
where
  "id" = $1
  and "leaseToken" = $2
  and "status" in ($3, $4, $5, $6, $7, $8)
returning
  "id"

-- TakeoutRepository.setRunStatusCas
update "takeout_run"
set
  "status" = $1,
  "updatedAt" = now()
where
  "id" = $2
  and "leaseToken" = $3
  and "status" in ($4, $5, $6, $7, $8, $9)
returning
  "id"

-- TakeoutRepository.finishRunCas
update "takeout_run"
set
  "status" = $1,
  "leaseToken" = $2,
  "updatedAt" = now()
where
  "id" = $3
  and "status" in ($4)
returning
  "id"

-- TakeoutRepository.claimRunForCancel
update "takeout_run"
set
  "status" = $1,
  "leaseToken" = $2,
  "heartbeatAt" = now(),
  "updatedAt" = now()
where
  "id" = $3
  and "status" in ($4)
  and (
    "leaseToken" is null
    or "leaseToken" = $5
    or "heartbeatAt" is null
    or "heartbeatAt" < now() - interval '60 seconds'
  )
returning
  "id"

-- TakeoutRepository.renewCancelLease
update "takeout_run"
set
  "heartbeatAt" = now()
where
  "id" = $1
  and "leaseToken" = $2
  and "status" = $3
returning
  "id"

-- TakeoutRepository.requestCancel
update "takeout_run"
set
  "status" = $1,
  "updatedAt" = now()
where
  "id" = $2
  and "status" in ($3, $4, $5, $6, $7, $8)
returning
  "id"

-- TakeoutRepository.getInterruptedRuns
select
  *
from
  "takeout_run"
where
  "status" in ($1, $2, $3, $4, $5, $6, $7)

-- TakeoutRepository.getActiveRunsByUser
select
  *
from
  "takeout_run"
where
  "userId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7, $8)

-- TakeoutRepository.takeLease
update "takeout_run"
set
  "heartbeatAt" = now(),
  "leaseToken" = $1
where
  "id" = $2
  and "status" in ($3, $4, $5, $6, $7, $8)
  and (
    "leaseToken" is null
    or "leaseToken" = $9
    or "heartbeatAt" < now() - interval '60 seconds'
  )
returning
  "id"

-- TakeoutRepository.requeueRun
begin
update "takeout_run"
set
  "status" = $1,
  "error" = $2,
  "heartbeatAt" = $3,
  "leaseToken" = $4,
  "finishedAt" = $5,
  "attempt" = $6,
  "updatedAt" = now()
where
  "id" = $7
  and "status" in ($8, $9)
  and "supersededBy" is null
returning
  "id"
commit

-- TakeoutRepository.claimExpiredStaging
update "takeout_run"
set
  "hasStaging" = $1,
  "updatedAt" = now()
where
  "id" = $2
  and "status" in ($3, $4)
  and "finishedAt" < now() - $5::interval
returning
  "id"

-- TakeoutRepository.getStoppedRunsWithTargets
select
  *
from
  "takeout_run"
where
  "supersededBy" is null
  and (
    (
      "takeout_run"."status" in ($1, $2)
      and exists (
        select
          "takeout_run_file"."id"
        from
          "takeout_run_file"
        where
          "takeout_run_file"."runId" = "takeout_run"."id"
          and "takeout_run_file"."action" = $3
          and "takeout_run_file"."targetPath" is not null
          and "takeout_run_file"."status" in ($4, $5, $6, $7)
          and not exists (
            select
              "asset"."id"
            from
              "asset"
            where
              "asset"."id" = "takeout_run_file"."newAssetId"
          )
      )
    )
    or (
      "takeout_run"."status" = $8
      and exists (
        select
          "takeout_run_file"."id"
        from
          "takeout_run_file"
        where
          "takeout_run_file"."runId" = "takeout_run"."id"
          and "takeout_run_file"."action" = $9
          and "takeout_run_file"."targetPath" is not null
          and "takeout_run_file"."status" in ($10)
          and not exists (
            select
              "asset"."id"
            from
              "asset"
            where
              "asset"."id" = "takeout_run_file"."newAssetId"
          )
      )
    )
  )

-- TakeoutRepository.updateRunFile
update "takeout_run_file"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.skipOpenRunFiles
update "takeout_run_file"
set
  "status" = $1,
  "fallbacks" = array_append(array_remove("fallbacks", $2::text), $3::text),
  "updatedAt" = now()
where
  "runId" = $4
  and "status" in ($5, $6)
  and "targetPath" is null

-- TakeoutRepository.getRunFilesForImport
select
  *
from
  "takeout_run_file"
where
  "runId" = $1
order by
  "seq" asc

-- TakeoutRepository.countRunFiles
select
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1

-- TakeoutRepository.countRunFilesByStatus
select
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1
  and "status" = $2

-- TakeoutRepository.getCounterRows
select
  "action",
  "status",
  "fileKind",
  "matcher",
  "fallbacks",
  "rotationState",
  "isCover",
  "groupKind",
  "reason",
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1
group by
  "action",
  "status",
  "fileKind",
  "matcher",
  "fallbacks",
  "rotationState",
  "isCover",
  "groupKind",
  "reason"

-- TakeoutRepository.getRotationCounts
select
  "rotationState",
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1
  and "rotationState" is not null
group by
  "rotationState"

-- TakeoutRepository.getRunFilesWithTarget
select
  "id",
  "seq",
  "action",
  "status",
  "targetPath",
  "newAssetId",
  "size",
  "checksum",
  "entrySeq"
from
  "takeout_run_file"
where
  "runId" = $1
  and "targetPath" is not null

-- TakeoutRepository.getPendingRotations
select
  "id",
  "rotation"
from
  "takeout_run_file"
where
  "assetId" = $1
  and "rotationState" = $2

-- TakeoutRepository.insertLargerVersion
insert into
  "takeout_larger_version" ("userId", "largerAssetId", "smallerAssetId")
values
  ($1, $2, $3)
on conflict do nothing

-- TakeoutRepository.getLargerVersion
select
  *
from
  "takeout_larger_version"
where
  "id" = $1

-- TakeoutRepository.getLargerVersions
select
  *
from
  "takeout_larger_version"
where
  "userId" = $1
order by
  "createdAt" desc

-- TakeoutRepository.countPendingLargerVersions
select
  count(*) as "count"
from
  "takeout_larger_version"
where
  "userId" = $1
  and "status" = $2

-- TakeoutRepository.updateLargerVersion
update "takeout_larger_version"
set
where
  "id" = $1

-- TakeoutRepository.getUploadAssetsByChecksums
select
  "id",
  "checksum",
  "deletedAt",
  "originalPath"
from
  "asset"
where
  "ownerId" = $1
  and "libraryId" is null
  and "checksum" in ($2)

-- TakeoutRepository.getPostImportState
select
  "asset"."id" as "id",
  "asset"."type" as "type",
  "asset"."thumbhash" is not null as "hasThumbhash",
  "asset_job_status"."metadataExtractedAt" is not null as "metadataDone",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
  ) as "hasPreview",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'thumbnail'
  ) as "hasThumbnail",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'encoded_video'
  ) as "hasEncodedVideo"
from
  "asset"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
where
  "asset"."id" in ($1)
  and "asset"."deletedAt" is null
