-- NOTE: This file is auto generated by ./sql-generator

-- TakeoutRepository.getFolder
select
  *
from
  "takeout_folder"
where
  "userId" = $1

-- TakeoutRepository.getAllFolders
select
  "userId",
  "folderName"
from
  "takeout_folder"

-- TakeoutRepository.createFolder
insert into
  "takeout_folder" ("userId", "folderName")
values
  ($1, $2)
returning
  *

-- TakeoutRepository.deleteFolder
delete from "takeout_folder"
where
  "userId" = $1

-- TakeoutRepository.getOrphanFolders
select
  "takeout_folder"."userId" as "userId",
  "takeout_folder"."folderName" as "folderName"
from
  "takeout_folder"
  left join "user" on "user"."id" = "takeout_folder"."userId"
where
  "user"."id" is null

-- TakeoutRepository.getSettings
select
  "settings"
from
  "takeout_settings"
where
  "userId" = $1

-- TakeoutRepository.upsertSettings
insert into
  "takeout_settings" ("userId", "settings", "updatedAt")
values
  ($1, $2, now())
on conflict ("userId") do update
set
  "settings" = "excluded"."settings",
  "updatedAt" = now()

-- TakeoutRepository.createUpload
insert into
  "takeout_upload" ("userId", "fileName", "size")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.getUpload
select
  *
from
  "takeout_upload"
where
  "id" = $1

-- TakeoutRepository.getUploadByName
select
  *
from
  "takeout_upload"
where
  "userId" = $1
  and "fileName" = $2

-- TakeoutRepository.getUploads
select
  *
from
  "takeout_upload"
where
  "userId" = $1
order by
  "createdAt" asc

-- TakeoutRepository.getAllUploads
select
  "id",
  "userId",
  "fileName",
  "size"
from
  "takeout_upload"

-- TakeoutRepository.touchUpload
update "takeout_upload"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.deleteUpload
delete from "takeout_upload"
where
  "id" = $1

-- TakeoutRepository.getExportsByUser
select
  *
from
  "takeout_export"
where
  "userId" = $1
order by
  "exportedAt" desc

-- TakeoutRepository.getExport
select
  *
from
  "takeout_export"
where
  "id" = $1

-- TakeoutRepository.createExport
insert into
  "takeout_export" ("userId", "exportKey", "exportedAt")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.updateExport
update "takeout_export"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.deleteExport
delete from "takeout_export"
where
  "id" = $1

-- TakeoutRepository.getExportsNeedingAnalysis
select
  "id"
from
  "takeout_export"
where
  (
    "analyzedAt" is null
    or "analysisInputsAt" > "analyzedAt"
  )
  and "analysisInputsAt" is not null

-- TakeoutRepository.getPartsByUser
select
  *
from
  "takeout_part"
where
  "userId" = $1

-- TakeoutRepository.getPartsByExport
select
  *
from
  "takeout_part"
where
  "exportId" = $1
order by
  "segment" asc nulls first,
  "partNumber" asc

-- TakeoutRepository.getPart
select
  *
from
  "takeout_part"
where
  "id" = $1

-- TakeoutRepository.createPart
insert into
  "takeout_part" ("exportId", "userId", "fileName")
values
  ($1, $2, $3)
returning
  *

-- TakeoutRepository.updatePart
update "takeout_part"
set
where
  "id" = $1

-- TakeoutRepository.deletePart
delete from "takeout_part"
where
  "id" = $1

-- TakeoutRepository.claimPart
update "takeout_part"
set
  "scanStatus" = $1,
  "scanOwner" = $2,
  "scanStartSize" = size,
  "scanStartMtime" = mtime,
  "scanStartCtime" = ctime,
  "heartbeatAt" = now(),
  "bytesScanned" = $3
where
  "id" = $4
  and "scanStatus" = $5
returning
  *

-- TakeoutRepository.getNextPendingPart
select
  *
from
  "takeout_part"
where
  "exportId" = $1
  and "scanStatus" = $2
  and "isIndex" = $3
order by
  "segment" asc nulls first,
  "partNumber" asc
limit
  $4

-- TakeoutRepository.deleteEntriesOfPart
delete from "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.deleteEntriesOfPartFromSeq
delete from "takeout_entry"
where
  "partId" = $1
  and "seq" >= $2

-- TakeoutRepository.getMaxEntrySeq
select
  max("seq") as "maxSeq"
from
  "takeout_entry"
where
  "partId" = $1

-- TakeoutRepository.deleteEntriesOfExport
delete from "takeout_entry"
where
  "exportId" = $1

-- TakeoutRepository.getMediaEntryPaths
select
  "path"
from
  "takeout_entry"
where
  "exportId" = $1
  and "kind" = $2

-- TakeoutRepository.getMediaBytes
select
  sum("size") as "bytes"
from
  "takeout_entry"
where
  "exportId" = $1
  and "kind" = $2

-- TakeoutRepository.createRun
insert into
  "takeout_run" ("userId", "exportId")
values
  ($1, $2)
returning
  *

-- TakeoutRepository.getRun
select
  *
from
  "takeout_run"
where
  "id" = $1

-- TakeoutRepository.getRunsByExport
select
  *
from
  "takeout_run"
where
  "exportId" = $1
order by
  "createdAt" desc

-- TakeoutRepository.getActiveRun
select
  *
from
  "takeout_run"
where
  "userId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7)
order by
  "createdAt" desc

-- TakeoutRepository.getActiveRunForExport
select
  *
from
  "takeout_run"
where
  "exportId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7)

-- TakeoutRepository.updateRun
update "takeout_run"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.getInterruptedRuns
select
  *
from
  "takeout_run"
where
  "status" in ($1, $2, $3, $4, $5, $6)

-- TakeoutRepository.getActiveRunsByUser
select
  *
from
  "takeout_run"
where
  "userId" = $1
  and "status" in ($2, $3, $4, $5, $6, $7)

-- TakeoutRepository.takeLease
update "takeout_run"
set
  "heartbeatAt" = now(),
  "leaseToken" = $1
where
  "id" = $2
  and (
    "leaseToken" is null
    or "leaseToken" = $3
    or "heartbeatAt" < now() - interval '60 seconds'
  )
returning
  "id"

-- TakeoutRepository.updateRunFile
update "takeout_run_file"
set
  "updatedAt" = now()
where
  "id" = $1

-- TakeoutRepository.getRunFilesForImport
select
  *
from
  "takeout_run_file"
where
  "runId" = $1
order by
  "seq" asc

-- TakeoutRepository.countRunFiles
select
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1

-- TakeoutRepository.getCounterRows
select
  "action",
  "status",
  "fileKind",
  "matcher",
  "fallbacks",
  "rotationState",
  "isCover",
  "groupKind",
  "reason",
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1
group by
  "action",
  "status",
  "fileKind",
  "matcher",
  "fallbacks",
  "rotationState",
  "isCover",
  "groupKind",
  "reason"

-- TakeoutRepository.getRotationCounts
select
  "rotationState",
  count(*) as "count"
from
  "takeout_run_file"
where
  "runId" = $1
  and "rotationState" is not null
group by
  "rotationState"

-- TakeoutRepository.getRunFilesWithTargetPath
select
  "id",
  "targetPath",
  "status"
from
  "takeout_run_file"
where
  "runId" = $1
  and "targetPath" is not null

-- TakeoutRepository.getPendingRotations
select
  "id",
  "rotation"
from
  "takeout_run_file"
where
  "assetId" = $1
  and "rotationState" = $2

-- TakeoutRepository.insertLargerVersion
insert into
  "takeout_larger_version" ("userId", "largerAssetId", "smallerAssetId")
values
  ($1, $2, $3)
on conflict do nothing

-- TakeoutRepository.getLargerVersion
select
  *
from
  "takeout_larger_version"
where
  "id" = $1

-- TakeoutRepository.getLargerVersions
select
  *
from
  "takeout_larger_version"
where
  "userId" = $1
order by
  "createdAt" desc

-- TakeoutRepository.countPendingLargerVersions
select
  count(*) as "count"
from
  "takeout_larger_version"
where
  "userId" = $1
  and "status" = $2

-- TakeoutRepository.updateLargerVersion
update "takeout_larger_version"
set
where
  "id" = $1

-- TakeoutRepository.getUploadAssetsByChecksums
select
  "id",
  "checksum",
  "deletedAt"
from
  "asset"
where
  "ownerId" = $1
  and "libraryId" is null
  and "checksum" in ($2)

-- TakeoutRepository.getPostImportState
select
  "asset"."id" as "id",
  "asset"."type" as "type",
  "asset"."thumbhash" is not null as "hasThumbhash",
  "asset_job_status"."metadataExtractedAt" is not null as "metadataDone",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
  ) as "hasPreview",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'thumbnail'
  ) as "hasThumbnail",
  exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'encoded_video'
  ) as "hasEncodedVideo"
from
  "asset"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
where
  "asset"."id" in ($1)
  and "asset"."deletedAt" is null
