-- NOTE: This file is auto generated by ./sql-generator

-- VideoBookmarkRepository.getByAssetId
select
  *
from
  "video_bookmark"
where
  "assetId" = $1
  and "userId" = $2
order by
  "time" asc,
  "createdAt" asc

-- VideoBookmarkRepository.get
select
  *
from
  "video_bookmark"
where
  "id" = $1

-- VideoBookmarkRepository.create
insert into
  "video_bookmark" ("assetId", "userId", "time", "label")
values
  ($1, $2, $3, $4)
returning
  *

-- VideoBookmarkRepository.update
update "video_bookmark"
set
  "time" = $1,
  "label" = $2
where
  "id" = $3
returning
  *

-- VideoBookmarkRepository.delete
delete from "video_bookmark"
where
  "id" = $1
